(function(){
'use strict';
const TILE=2.25, SIZE=45, WALL=1, FLOOR=0;
const $=s=>document.querySelector(s);
function fatal(err){console.error(err);$('#fatal-message').textContent=String(err&&err.stack||err);$('#fatal-screen').hidden=false;$('#fatal-screen').classList.add('visible');}
window.addEventListener('error',e=>fatal(e.error||e.message));
window.addEventListener('unhandledrejection',e=>fatal(e.reason));

class RNG{constructor(seed){this.s=this.hash(seed)||1}hash(t){let h=2166136261;for(const c of String(t)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}next(){let x=this.s;x^=x<<13;x^=x>>>17;x^=x<<5;this.s=x>>>0;return this.s/4294967296}int(a,b){return Math.floor(this.next()*(b-a+1))+a}shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=this.int(0,i);[a[i],a[j]]=[a[j],a[i]]}return a}}
function dungeon(seed){const r=new RNG(seed),cw=15,ch=15,c=Array.from({length:ch},()=>Array(cw).fill(WALL)),st=[[1,1]];c[1][1]=FLOOR;while(st.length){const [x,y]=st[st.length-1],n=r.shuffle([[2,0],[-2,0],[0,2],[0,-2]]).find(([dx,dy])=>x+dx>0&&y+dy>0&&x+dx<cw-1&&y+dy<ch-1&&c[y+dy][x+dx]===WALL);if(!n){st.pop();continue}const[dx,dy]=n;c[y+dy/2][x+dx/2]=FLOOR;c[y+dy][x+dx]=FLOOR;st.push([x+dx,y+dy])}const g=Array.from({length:SIZE},()=>Array(SIZE).fill(WALL));for(let y=0;y<ch;y++)for(let x=0;x<cw;x++)if(c[y][x]===FLOOR)for(let oy=0;oy<3;oy++)for(let ox=0;ox<3;ox++){const gx=x*3+ox,gy=y*3+oy;if(gx>0&&gy>0&&gx<SIZE-1&&gy<SIZE-1)g[gy][gx]=FLOOR}
// Salas irregulares conectadas al laberinto.
for(let i=0;i<10;i++){const w=r.int(5,10),h=r.int(5,9),x=r.int(2,SIZE-w-3),y=r.int(2,SIZE-h-3);for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)g[yy][xx]=FLOOR}
// Abre las cuatro fronteras; al cruzarlas se genera otro sector determinista.
for(let k=-1;k<=1;k++){g[1][Math.floor(SIZE/2)+k]=FLOOR;g[SIZE-2][Math.floor(SIZE/2)+k]=FLOOR;g[Math.floor(SIZE/2)+k][1]=FLOOR;g[Math.floor(SIZE/2)+k][SIZE-2]=FLOOR}
return g}
function tex(kind){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),r=new RNG(kind);x.fillStyle=kind==='floor'?'#373129':'#51483b';x.fillRect(0,0,128,128);if(kind==='wall'){for(let y=0;y<128;y+=32){for(let xx=(y/32%2)*-20;xx<128;xx+=48){x.strokeStyle='#271f18';x.lineWidth=3;x.strokeRect(xx,y,48,32)}}}for(let i=0;i<700;i++){const v=r.int(25,85);x.fillStyle=`rgba(${v},${Math.floor(v*.85)},${Math.floor(v*.65)},${r.next()*.16})`;x.fillRect(r.int(0,127),r.int(0,127),r.int(1,3),r.int(1,3))}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(1.6,1.6);t.magFilter=THREE.NearestFilter;return t}
function playerTex(){const c=document.createElement('canvas');c.width=32;c.height=48;const x=c.getContext('2d');x.imageSmoothingEnabled=false;x.fillStyle='#1a1611';x.fillRect(9,4,14,13);x.fillStyle='#caa47d';x.fillRect(12,8,8,8);x.fillStyle='#3c291d';x.fillRect(8,17,16,18);x.fillStyle='#7e5f38';x.fillRect(10,18,12,11);x.fillStyle='#201812';x.fillRect(4,20,5,14);x.fillRect(23,20,5,14);x.fillRect(9,35,6,11);x.fillRect(17,35,6,11);const t=new THREE.CanvasTexture(c);t.magFilter=THREE.NearestFilter;t.minFilter=THREE.NearestFilter;return t}
class Game{constructor(){if(!window.THREE)throw new Error('Three.js no se cargó. Comprueba js/vendor/three.min.js');this.canvas=$('#game');this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.5));this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x080706);this.scene.fog=new THREE.FogExp2(0x080706,.022);this.camera=new THREE.PerspectiveCamera(58,1,.1,180);this.clock=new THREE.Clock();this.keys=new Set;this.angle=Math.PI/4;this.floor=1;this.sx=0;this.sy=0;this.seed='dungeon-001';this.pos=new THREE.Vector3;this.vel=new THREE.Vector3;this.world=new THREE.Group;this.scene.add(this.world);this.scene.add(new THREE.HemisphereLight(0x80745e,0x110d08,1.25));this.light=new THREE.PointLight(0xffb45f,2.8,18,2);this.scene.add(this.light);const pm=new THREE.SpriteMaterial({map:playerTex(),transparent:true,alphaTest:.05});this.player=new THREE.Sprite(pm);this.player.scale.set(1.65,2.5,1);this.player.center.set(.5,.08);this.scene.add(this.player);this.bind();this.resize();addEventListener('resize',()=>this.resize())}
bind(){const m={KeyW:'forward',ArrowUp:'forward',KeyS:'back',ArrowDown:'back',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right',KeyQ:'turnLeft',KeyE:'turnRight'};addEventListener('keydown',e=>{if(m[e.code]){e.preventDefault();this.keys.add(m[e.code])}});addEventListener('keyup',e=>{if(m[e.code])this.keys.delete(m[e.code])});document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key,down=e=>{e.preventDefault();this.keys.add(k)},up=e=>{e.preventDefault();this.keys.delete(k)};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('pointerleave',up)})}
build(seed,floor,sx=0,sy=0,entry='center'){this.seed=seed;this.floor=floor;this.sx=sx;this.sy=sy;this.grid=dungeon(`${seed}:${floor}:${sx}:${sy}`);while(this.world.children.length){const o=this.world.children.pop();if(o.geometry)o.geometry.dispose()}const fg=new THREE.BoxGeometry(TILE,.18,TILE),wg=new THREE.BoxGeometry(TILE,3.8,TILE),fm=new THREE.MeshStandardMaterial({map:tex('floor'),roughness:.96}),wm=new THREE.MeshStandardMaterial({map:tex('wall'),roughness:.92});const floors=[],walls=[];for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const wx=(x-SIZE/2)*TILE,wz=(y-SIZE/2)*TILE;if(this.grid[y][x]===FLOOR)floors.push([wx,-.1,wz]);else if([[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>this.grid[y+dy]&&this.grid[y+dy][x+dx]===FLOOR))walls.push([wx,1.9,wz])}const d=new THREE.Object3D,fi=new THREE.InstancedMesh(fg,fm,floors.length),wi=new THREE.InstancedMesh(wg,wm,walls.length);floors.forEach((p,i)=>{d.position.set(...p);d.updateMatrix();fi.setMatrixAt(i,d.matrix)});walls.forEach((p,i)=>{d.position.set(...p);d.updateMatrix();wi.setMatrixAt(i,d.matrix)});this.world.add(fi,wi);const starts={center:[Math.floor(SIZE/2),Math.floor(SIZE/2)],north:[Math.floor(SIZE/2),SIZE-4],south:[Math.floor(SIZE/2),3],west:[SIZE-4,Math.floor(SIZE/2)],east:[3,Math.floor(SIZE/2)]};let [tx,ty]=starts[entry]||starts.center;if(this.grid[ty][tx]!==FLOOR){outer:for(let r=0;r<SIZE;r++)for(let y=1;y<SIZE-1;y++)for(let x=1;x<SIZE-1;x++)if(this.grid[y][x]===FLOOR&&Math.abs(x-tx)+Math.abs(y-ty)<=r){tx=x;ty=y;break outer}}this.pos.set((tx-SIZE/2)*TILE,0,(ty-SIZE/2)*TILE);this.player.position.copy(this.pos);$('#floor-value').textContent=floor;$('#sector-value').textContent=`${sx}, ${sy}`;$('#seed-value').textContent=seed;this.drawMap();this.say(`Sector ${sx}, ${sy}`)}
wt(x,z){return{x:Math.round(x/TILE+SIZE/2),y:Math.round(z/TILE+SIZE/2)}}can(x,z){const r=.42;for(const[ox,oz]of[[-r,-r],[r,-r],[-r,r],[r,r]]){const t=this.wt(x+ox,z+oz);if(this.grid[t.y]&&this.grid[t.y][t.x]!==FLOOR)return false}return true}
transition(){const lim=(SIZE/2-1.9)*TILE;if(this.pos.z<-lim){this.build(this.seed,this.floor,this.sx,this.sy-1,'north');return true}if(this.pos.z>lim){this.build(this.seed,this.floor,this.sx,this.sy+1,'south');return true}if(this.pos.x<-lim){this.build(this.seed,this.floor,this.sx-1,this.sy,'west');return true}if(this.pos.x>lim){this.build(this.seed,this.floor,this.sx+1,this.sy,'east');return true}return false}
update(dt){const turn=(this.keys.has('turnLeft')?1:0)-(this.keys.has('turnRight')?1:0);this.angle+=turn*dt*1.8;const f=new THREE.Vector3(-Math.sin(this.angle),0,-Math.cos(this.angle)),r=new THREE.Vector3(Math.cos(this.angle),0,-Math.sin(this.angle)),i=new THREE.Vector3;if(this.keys.has('forward'))i.add(f);if(this.keys.has('back'))i.sub(f);if(this.keys.has('right'))i.add(r);if(this.keys.has('left'))i.sub(r);if(i.lengthSq())i.normalize().multiplyScalar(5.7);this.vel.lerp(i,Math.min(1,dt*10));const nx=this.pos.x+this.vel.x*dt,nz=this.pos.z+this.vel.z*dt;if(this.can(nx,this.pos.z))this.pos.x=nx;if(this.can(this.pos.x,nz))this.pos.z=nz;this.player.position.copy(this.pos);this.light.position.set(this.pos.x,1.6,this.pos.z);const off=new THREE.Vector3(Math.sin(this.angle)*10.5,9.5,Math.cos(this.angle)*10.5);this.camera.position.lerp(this.pos.clone().add(off),1-Math.pow(.002,dt));this.camera.lookAt(this.pos.x,1,this.pos.z);this.transition();this.drawMap()}
drawMap(){const c=$('#minimap'),x=c.getContext('2d'),s=c.width/SIZE;x.fillStyle='#080706';x.fillRect(0,0,c.width,c.height);x.fillStyle='#6e6250';for(let y=0;y<SIZE;y++)for(let xx=0;xx<SIZE;xx++)if(this.grid[y][xx]===FLOOR)x.fillRect(xx*s,y*s,Math.ceil(s),Math.ceil(s));const p=this.wt(this.pos.x,this.pos.z);x.fillStyle='#ffd98c';x.beginPath();x.arc(p.x*s,p.y*s,3,0,Math.PI*2);x.fill()}
say(t){const e=$('#message');e.textContent=t;e.classList.add('show');clearTimeout(this.mt);this.mt=setTimeout(()=>e.classList.remove('show'),1800)}resize(){this.renderer.setSize(innerWidth,innerHeight,false);this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix()}start(){if(this.running)return;this.running=true;this.clock.start();const loop=()=>{requestAnimationFrame(loop);const dt=Math.min(.05,this.clock.getDelta());this.update(dt);this.renderer.render(this.scene,this.camera)};loop()}}

document.addEventListener('DOMContentLoaded',()=>{try{const game=new Game;$('#boot-status').textContent='Motor listo. Pulsa ENTRAR.';const launch=()=>{const seed=$('#seed-input').value.trim()||`dungeon-${Date.now()}`;$('#start-screen').classList.remove('visible');$('#start-screen').hidden=true;$('#hud').hidden=false;$('#minimap').style.display='block';game.build(seed,1,0,0);game.start()};$('#start-button').addEventListener('click',launch);$('#seed-input').addEventListener('keydown',e=>{if(e.key==='Enter')launch()});$('#new-map-button').addEventListener('click',()=>game.build(`${game.seed}-${Date.now().toString(36)}`,1,0,0));$('#reload-button').addEventListener('click',()=>location.reload())}catch(e){fatal(e)}});
})();
